[device]
profile = "cx505_sim"
use_profile_defaults = false
transport = "sim"
index = 0
baud = 115200
data_bits = 8
stop_bits = 2.0
parity = "E"
poll_hex = "01 23 30 23 30 23 30 23 03"
poll_interval_s = 1.0
latency_timer_ms = 2
read_timeout_ms = 500
write_timeout_ms = 500
chunk_size = 256

[acquisition]
window_s = 2.0
idle_s = 1.0
restart_delay_s = 2.0
status_interval_s = 5.0
default_command_max_retries = 1
default_command_retry_backoff_s = 1.0
decode_failure_threshold = 3
startup_commands = []

[storage]
database_path = "data/bench_harness.sqlite"
ensure_directories = true
vacuum_on_start = false
retention_days = null

[ingestion]
annotate_device = true
enrich_with_timestamp = true
emit_raw_frame = true

[analytics]
enabled = true
moving_average_window = 5
stability_window = 12
temperature_coefficient = 0.0
reference_temperature = 25.0
profiling_enabled = true
max_frames_per_minute = 120

[monitoring]
log_rotation_task = ""
log_rotation_max_age_minutes = 0
log_rotation_probe_interval_s = 120
