"""Collect installed dependency license metadata/texts for release redistribution."""
import importlib.metadata as metadata
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'third_party'


def safe(value):
    return re.sub(r'[^A-Za-z0-9_.-]', '_', value)


def copy_license(source, package, files):
    target = OUT / 'licenses' / safe(package) / (hashlib.sha256(source.read_bytes()).hexdigest()[:12]+'-'+source.name)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, target)
    files.append(str(target.relative_to(OUT)).replace('\\', '/'))


def main():
    OUT.mkdir(exist_ok=True)
    python = []
    for dist in sorted(metadata.distributions(), key=lambda d: d.metadata['Name'].lower()):
        name = dist.metadata['Name']
        if name == 'elmetron-data-capture':
            continue
        files = []
        for relative in dist.files or []:
            path = Path(dist.locate_file(relative))
            if path.is_file() and any(t in path.name.lower() for t in ('license', 'licence', 'copying', 'notice')):
                copy_license(path, 'python-' + name, files)
        python.append({'name': name, 'version': dist.version,
                       'license': dist.metadata.get('License-Expression') or dist.metadata.get('License') or
                       [v for v in dist.metadata.get_all('Classifier', []) if v.startswith('License ::')],
                       'files': sorted(set(files))})
    # CPython runtime's license covers the bundled interpreter and bundled third-party notices.
    interpreter_license = Path(sys.base_prefix) / 'LICENSE.txt'
    if not interpreter_license.exists():
        interpreter_license = Path(sys.base_prefix) / 'lib/python3.13/LICENSE.txt'
    if interpreter_license.exists():
        copy_license(interpreter_license, 'CPython', [])
    npm = []
    lock = json.loads((ROOT / 'ui/package-lock.json').read_text(encoding='utf-8'))
    for location, info in lock['packages'].items():
        if not location:
            continue
        folder = ROOT / 'ui' / location
        manifest = folder / 'package.json'
        if not manifest.exists():
            continue
        package = json.loads(manifest.read_text(encoding='utf-8'))
        name = package.get('name', location)
        files = []
        for path in folder.iterdir():
            if path.is_file() and any(t in path.name.lower() for t in ('license', 'licence', 'copying', 'notice')):
                copy_license(path, 'npm-' + name + '-' + info.get('version', ''), files)
        npm.append({'name':name,'version':info.get('version'),'license':package.get('license',info.get('license')),
                    'development_only':info.get('dev',False),'files':files})
    (OUT/'inventory.json').write_text(json.dumps({'python':python,'npm':npm},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    (OUT/'README.md').write_text('# Bundled dependency notices\n\nGenerated by `scripts/collect_licenses.py` from the locked build environment.\n'
        'See inventory.json for dependency versions, declared licenses and license text paths.\n'
        'Build/test dependencies are included for transparency; their presence here does not mean\n'
        'they are included in the installed runtime. CPython and DejaVu notices are supplied separately.\n',encoding='utf-8')
    print(f'Collected {len(python)} Python and {len(npm)} npm dependency inventories')


if __name__ == '__main__':
    main()
